# XDC For 1600Mbps LVDS rate
create_clock -period 10.000 [get_ports clk_100m_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports clk_100m_p]

set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_clk_p[*]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {rx_data_p[*]}]
set_property DIFF_TERM_ADV TERM_100 [get_ports {strobe_rx_p[*]}]

create_clock -period 1.250 [get_ports {rx_clk_p[0]}]
create_clock -period 1.250 [get_ports {rx_clk_p[1]}]
create_clock -period 1.250 [get_ports {rx_clk_p[2]}]
create_clock -period 1.250 [get_ports {rx_clk_p[3]}]

set_property IOSTANDARD LVDS_25 [get_ports clk_100m_p]
set_property IOSTANDARD LVDS_25 [get_ports clk_100m_n]
set_property PACKAGE_PIN AL19 [get_ports clk_100m_p]
set_property PACKAGE_PIN AL18 [get_ports clk_100m_n]

set_property IOSTANDARD LVCMOS25 [get_ports hw_rst_n]
set_property PACKAGE_PIN AE15 [get_ports hw_rst_n]

set_property IOSTANDARD LVCMOS18 [get_ports rx_sync]
set_property PACKAGE_PIN AL39 [get_ports rx_sync]

#User LEDs
set_property IOSTANDARD LVCMOS25 [get_ports rx_rst_done_led]
set_property PACKAGE_PIN AE18 [get_ports rx_rst_done_led]

set_false_path -to [get_ports rx_rst_done_led]

#connections to avoid logic optimization for lrx data wires- should be removed when utilizing the lrx bus interface
set_property IOSTANDARD LVCMOS18 [get_ports and_of_all_busdata]
set_property PACKAGE_PIN AK36 [get_ports and_of_all_busdata]

#adc data signals IO standard
#bank 0 data lanes
set_property IOSTANDARD LVDS [get_ports {rx_data_p[0]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[1]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[2]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[3]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[4]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[5]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[6]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[7]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[8]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[9]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[10]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[11]}]
#bank 1 data lanes
set_property IOSTANDARD LVDS [get_ports {rx_data_p[12]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[13]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[14]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[15]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[16]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[17]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[18]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[19]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[20]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[21]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[22]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[23]}]
#bank 2 data lanes
set_property IOSTANDARD LVDS [get_ports {rx_data_p[24]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[25]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[26]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[27]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[28]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[29]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[30]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[31]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[32]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[33]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[34]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[35]}]
#bank 3 data lanes
set_property IOSTANDARD LVDS [get_ports {rx_data_p[36]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[37]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[38]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[39]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[40]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[41]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[42]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[43]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[44]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[45]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[46]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_p[47]}]
#adc clk signals IO standard
#bank 0 frwd clk lanes
set_property IOSTANDARD LVDS [get_ports {rx_clk_p[0]}]
set_property IOSTANDARD LVDS [get_ports {rx_clk_n[0]}]
#bank 1 frwd clk lanes
set_property IOSTANDARD LVDS [get_ports {rx_clk_p[1]}]
set_property IOSTANDARD LVDS [get_ports {rx_clk_n[1]}]
#bank 2 frwd clk lanes
set_property IOSTANDARD LVDS [get_ports {rx_clk_p[2]}]
set_property IOSTANDARD LVDS [get_ports {rx_clk_n[2]}]
#bank 3 frwd clk lanes
set_property IOSTANDARD LVDS [get_ports {rx_clk_p[3]}]
set_property IOSTANDARD LVDS [get_ports {rx_clk_n[3]}]
#adc strobe signals IO standard
#bank 0 frwd strobe lanes
set_property IOSTANDARD LVDS [get_ports {strobe_rx_n[0]}]
set_property IOSTANDARD LVDS [get_ports {strobe_rx_p[0]}]
#bank 1 frwd strobe lanes
set_property IOSTANDARD LVDS [get_ports {strobe_rx_n[1]}]
set_property IOSTANDARD LVDS [get_ports {strobe_rx_p[1]}]
#bank 2 frwd strobe lanes
set_property IOSTANDARD LVDS [get_ports {strobe_rx_n[2]}]
set_property IOSTANDARD LVDS [get_ports {strobe_rx_p[2]}]
#bank 3 frwd strobe lanes
set_property IOSTANDARD LVDS [get_ports {strobe_rx_n[3]}]
set_property IOSTANDARD LVDS [get_ports {strobe_rx_p[3]}]

#adc signals pin declarations
#bank 0 data lanes
set_property PACKAGE_PIN AU39 [get_ports {rx_data_n[11]}]
set_property PACKAGE_PIN AT39 [get_ports {rx_data_p[11]}]
set_property PACKAGE_PIN AU36 [get_ports {rx_data_p[10]}]
set_property PACKAGE_PIN AV36 [get_ports {rx_data_n[10]}]
set_property PACKAGE_PIN AM35 [get_ports {rx_data_n[9]}]
set_property PACKAGE_PIN AM34 [get_ports {rx_data_p[9]}]
set_property PACKAGE_PIN AU35 [get_ports {rx_data_n[8]}]
set_property PACKAGE_PIN AT35 [get_ports {rx_data_p[8]}]
set_property PACKAGE_PIN AW33 [get_ports {rx_data_p[7]}]
set_property PACKAGE_PIN AW34 [get_ports {rx_data_n[7]}]
set_property PACKAGE_PIN AV37 [get_ports {rx_data_n[6]}]
set_property PACKAGE_PIN AU37 [get_ports {rx_data_p[6]}]
set_property PACKAGE_PIN AV38 [get_ports {rx_data_p[5]}]
set_property PACKAGE_PIN AV39 [get_ports {rx_data_n[5]}]
set_property PACKAGE_PIN AR37 [get_ports {rx_data_p[4]}]
set_property PACKAGE_PIN AT37 [get_ports {rx_data_n[4]}]
set_property PACKAGE_PIN AP39 [get_ports {rx_data_n[3]}]
set_property PACKAGE_PIN AN39 [get_ports {rx_data_p[3]}]
set_property PACKAGE_PIN AP38 [get_ports {rx_data_n[2]}]
set_property PACKAGE_PIN AN38 [get_ports {rx_data_p[2]}]
set_property PACKAGE_PIN AR38 [get_ports {rx_data_p[1]}]
set_property PACKAGE_PIN AT38 [get_ports {rx_data_n[1]}]
set_property PACKAGE_PIN AM37 [get_ports {rx_data_n[0]}]
set_property PACKAGE_PIN AM36 [get_ports {rx_data_p[0]}]
#bank 0 frwd clk lanes
set_property PACKAGE_PIN AP36 [get_ports {rx_clk_p[0]}]
set_property PACKAGE_PIN AR36 [get_ports {rx_clk_n[0]}]
#bank 0 frwd strobe lanes
set_property PACKAGE_PIN AN36 [get_ports {strobe_rx_p[0]}]
set_property PACKAGE_PIN AN37 [get_ports {strobe_rx_n[0]}]

#bank 1 data lanes
set_property PACKAGE_PIN AR21 [get_ports {rx_data_n[23]}]
set_property PACKAGE_PIN AP21 [get_ports {rx_data_p[23]}]
set_property PACKAGE_PIN AV21 [get_ports {rx_data_p[22]}]
set_property PACKAGE_PIN AW21 [get_ports {rx_data_n[22]}]
set_property PACKAGE_PIN AN21 [get_ports {rx_data_n[21]}]
set_property PACKAGE_PIN AM21 [get_ports {rx_data_p[21]}]
set_property PACKAGE_PIN AR22 [get_ports {rx_data_p[20]}]
set_property PACKAGE_PIN AR23 [get_ports {rx_data_n[20]}]
set_property PACKAGE_PIN AP23 [get_ports {rx_data_n[19]}]
set_property PACKAGE_PIN AN23 [get_ports {rx_data_p[19]}]
set_property PACKAGE_PIN AV24 [get_ports {rx_data_p[18]}]
set_property PACKAGE_PIN AW24 [get_ports {rx_data_n[18]}]
set_property PACKAGE_PIN AM22 [get_ports {rx_data_p[17]}]
set_property PACKAGE_PIN AN22 [get_ports {rx_data_n[17]}]
set_property PACKAGE_PIN AL20 [get_ports {rx_data_p[16]}]
set_property PACKAGE_PIN AM20 [get_ports {rx_data_n[16]}]
set_property PACKAGE_PIN AK21 [get_ports {rx_data_n[15]}]
set_property PACKAGE_PIN AK20 [get_ports {rx_data_p[15]}]
set_property PACKAGE_PIN AJ20 [get_ports {rx_data_p[14]}]
set_property PACKAGE_PIN AJ21 [get_ports {rx_data_n[14]}]
set_property PACKAGE_PIN AH23 [get_ports {rx_data_n[13]}]
set_property PACKAGE_PIN AH22 [get_ports {rx_data_p[13]}]
set_property PACKAGE_PIN AP24 [get_ports {rx_data_n[12]}]
set_property PACKAGE_PIN AN24 [get_ports {rx_data_p[12]}]
#bank 1 frwd clk lanes
set_property PACKAGE_PIN AK23 [get_ports {rx_clk_p[1]}]
set_property PACKAGE_PIN AL23 [get_ports {rx_clk_n[1]}]
#bank 1 strobe lanes
set_property PACKAGE_PIN AL22 [get_ports {strobe_rx_n[1]}]
set_property PACKAGE_PIN AK22 [get_ports {strobe_rx_p[1]}]

#bank 2 data lanes
set_property PACKAGE_PIN AV29 [get_ports {rx_data_p[35]}]
set_property PACKAGE_PIN AW29 [get_ports {rx_data_n[35]}]
set_property PACKAGE_PIN AN31 [get_ports {rx_data_n[34]}]
set_property PACKAGE_PIN AM31 [get_ports {rx_data_p[34]}]
set_property PACKAGE_PIN AT29 [get_ports {rx_data_p[33]}]
set_property PACKAGE_PIN AT30 [get_ports {rx_data_n[33]}]
set_property PACKAGE_PIN AN32 [get_ports {rx_data_n[32]}]
set_property PACKAGE_PIN AM32 [get_ports {rx_data_p[32]}]
set_property PACKAGE_PIN AP30 [get_ports {rx_data_p[31]}]
set_property PACKAGE_PIN AP31 [get_ports {rx_data_n[31]}]
set_property PACKAGE_PIN AR32 [get_ports {rx_data_n[30]}]
set_property PACKAGE_PIN AR31 [get_ports {rx_data_p[30]}]
set_property PACKAGE_PIN AU32 [get_ports {rx_data_p[29]}]
set_property PACKAGE_PIN AV32 [get_ports {rx_data_n[29]}]
set_property PACKAGE_PIN AJ30 [get_ports {rx_data_p[28]}]
set_property PACKAGE_PIN AK30 [get_ports {rx_data_n[28]}]
set_property PACKAGE_PIN AK31 [get_ports {rx_data_n[27]}]
set_property PACKAGE_PIN AJ31 [get_ports {rx_data_p[27]}]
set_property PACKAGE_PIN AK32 [get_ports {rx_data_p[26]}]
set_property PACKAGE_PIN AL32 [get_ports {rx_data_n[26]}]
set_property PACKAGE_PIN AK33 [get_ports {rx_data_n[25]}]
set_property PACKAGE_PIN AJ33 [get_ports {rx_data_p[25]}]
set_property PACKAGE_PIN AP33 [get_ports {rx_data_n[24]}]
set_property PACKAGE_PIN AN33 [get_ports {rx_data_p[24]}]
#bank 2 frwd clk lanes
set_property PACKAGE_PIN AL30 [get_ports {rx_clk_p[2]}]
set_property PACKAGE_PIN AM30 [get_ports {rx_clk_n[2]}]
#bank 2 strobe lanes
set_property PACKAGE_PIN AL29 [get_ports {strobe_rx_p[2]}]
set_property PACKAGE_PIN AM29 [get_ports {strobe_rx_n[2]}]

#bank 3 data lanes
set_property PACKAGE_PIN AM24 [get_ports {rx_data_p[47]}]
set_property PACKAGE_PIN AM25 [get_ports {rx_data_n[47]}]
set_property PACKAGE_PIN AN26 [get_ports {rx_data_n[46]}]
set_property PACKAGE_PIN AM26 [get_ports {rx_data_p[46]}]
set_property PACKAGE_PIN AR25 [get_ports {rx_data_n[45]}]
set_property PACKAGE_PIN AP25 [get_ports {rx_data_p[45]}]
set_property PACKAGE_PIN AP28 [get_ports {rx_data_n[44]}]
set_property PACKAGE_PIN AN28 [get_ports {rx_data_p[44]}]
set_property PACKAGE_PIN AW25 [get_ports {rx_data_p[43]}]
set_property PACKAGE_PIN AW26 [get_ports {rx_data_n[43]}]
set_property PACKAGE_PIN AV27 [get_ports {rx_data_n[42]}]
set_property PACKAGE_PIN AV26 [get_ports {rx_data_p[42]}]
set_property PACKAGE_PIN AV28 [get_ports {rx_data_p[41]}]
set_property PACKAGE_PIN AW28 [get_ports {rx_data_n[41]}]
set_property PACKAGE_PIN AJ24 [get_ports {rx_data_n[40]}]
set_property PACKAGE_PIN AH24 [get_ports {rx_data_p[40]}]
set_property PACKAGE_PIN AJ25 [get_ports {rx_data_p[39]}]
set_property PACKAGE_PIN AK25 [get_ports {rx_data_n[39]}]
set_property PACKAGE_PIN AL24 [get_ports {rx_data_p[38]}]
set_property PACKAGE_PIN AL25 [get_ports {rx_data_n[38]}]
set_property PACKAGE_PIN AJ26 [get_ports {rx_data_n[37]}]
set_property PACKAGE_PIN AH26 [get_ports {rx_data_p[37]}]
set_property PACKAGE_PIN AR27 [get_ports {rx_data_n[36]}]
set_property PACKAGE_PIN AR26 [get_ports {rx_data_p[36]}]
#bank 3 frwd clk lanes
set_property PACKAGE_PIN AK27 [get_ports {rx_clk_p[3]}]
set_property PACKAGE_PIN AK28 [get_ports {rx_clk_n[3]}]
#bank 3 strobe lanes
set_property PACKAGE_PIN AL27 [get_ports {strobe_rx_p[3]}]
set_property PACKAGE_PIN AL28 [get_ports {strobe_rx_n[3]}]

